EntertainmentTrackerPersonal/Controllers/AnimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainmentTrackerPersonal.Controllers
{
    public class AnimesController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Animes Home Page";

            return View();
        }

        public ActionResult AddAnimes()
        {
            ViewBag.Message = "Add More Animes";

            return View();
        }

        public ActionResult AnimesLibrary()
        {
            ViewBag.Message = "Animes you have add";

            return View();
        }
       
    }
}

EntertainmentTrackerPersonal/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainmentTrackerPersonal.Controllers
{
    public class BooksController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Books Home";

            return View();
        }

        public ActionResult AddBooks()
        {
            ViewBag.Message = "Too sexy";

            return View();
        }

        public ActionResult BooksLibrary()
        {
            ViewBag.Message = "Please Just dont";

            return View();
        }
       
       
    }
}

EntertainmentTrackerPersonal/Controllers/HomeController.cs
using System.Configuration;
using System.Web.Mvc;
using System.Web.Security;
using DataObjects;
using EntertainmentTrackerPersonal.WebHelpers;
using WebMatrix.WebData;

namespace EntertainmentTrackerPersonal.Controllers
{
    public class HomeController : Controller
    {
        WebServiceHelper _webHelper = new WebServiceHelper();

        [HttpPost]
        public ActionResult Login(User userModel)
        {
            string requestUrl = ConfigurationManager.AppSettings["RequestUrlForGet"];

            var status = _webHelper.GetUserData(requestUrl,userModel);

            if (status == UserServiceStatusCode.Ok)
            {
                    FormsAuthentication.SetAuthCookie(userModel.UserName, userModel.RememberMe);
                    return RedirectToAction("UserHome", "Users");
            }

            return View();
        }
        
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("UserHome", "Users");
            }

            return View();
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }

            return RedirectToAction("Login", "Home");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Too sexy";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Please Just dont";

            return View();
        }
    }
}

EntertainmentTrackerPersonal/Controllers/TVShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainmentTrackerPersonal.Controllers
{
    public class TVShowsController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "This Message comes from the controlelr and i dont like it";

            return View();
        }

        public ActionResult AddTVShows()
        {
            ViewBag.Message = "Too sexy";

            return View();
        }

        public ActionResult TVShowsLibrary()
        {
            ViewBag.Message = "Please Just dont";

            return View();
        }
       
    }
}

EntertainmentTrackerPersonal/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;


namespace EntertainmentTrackerPersonal.Controllers
{

    public class UsersController : Controller
    {
        public ActionResult UserHome()
        {
            if(User.Identity.IsAuthenticated)
            {
                ViewBag.Message = "This Is the user Home Page";

                return View();
            }

            return RedirectToAction("Login", "Home");
        }
    }
}

EntertainmentTrackerPersonal/Views/Animes/AddAnimes.cshtml
@{
    ViewBag.Title = "Add animes";
}

<h4>AddAnimes</h4>

EntertainmentTrackerPersonal/Views/Animes/AnimesLibrary.cshtml
@{
    ViewBag.Title = "Anime Lib";
}

<h4>Anime libb</h4>

EntertainmentTrackerPersonal/Views/Animes/Index.cshtml
@{
    ViewBag.Title = "Animes Home Page";
}

EntertainmentTrackerPersonal/Views/Books/AddBooks.cshtml
@{
    ViewBag.Title = "Add books";
}

<h4>add books</h4>

EntertainmentTrackerPersonal/Views/Books/BooksLibrary.cshtml
@{
    ViewBag.Title = "Books Lib";
}

<h4>Books you have added</h4>

EntertainmentTrackerPersonal/Views/Books/Index.cshtml
@{
    ViewBag.Title = "Animes Home Page";
}

EntertainmentTrackerPersonal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>
<p>
     Here is some Interesting Content. Yea you wish
</p>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Navigation</li>
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
</ul>

EntertainmentTrackerPersonal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>

<h3>Please dont contact us</h3>
<span>le fuck</span>

<h3>Email</h3>
<span><a href="mailto:darkelfbg@gmail.com">darkelfbg@gmail.com</a></span>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Navigation</li>
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("About", "About", "Home")</li>
</ul>

EntertainmentTrackerPersonal/Views/Home/Index.Phone.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>
<p>
    To learn more about ASP.NET MVC visit <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
</p>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Navigation</li>
    <li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
</ul>

EntertainmentTrackerPersonal/Views/Home/Index.Tablet.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>
<p>
    To learn more about ASP.NET MVC visit <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
</p>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Navigation</li>
    <li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
</ul>

EntertainmentTrackerPersonal/Views/Home/Login.cshtml
@model DataObjects.User

    @using(Html.BeginForm("Login","Home",FormMethod.Post,new {@class="form-horizontal"}))
     {
         <div class="well row">
          
               <div class="form-group">
                   <label for="UserName" class="col-sm-2 control-label">Username</label>
                   <div class="col-sm-4">
                       <input type="text" class="form-control" id="UserName" name="UserName" placeholder="UserName">
                   </div>
               </div>
               <div class="form-group">
                   <label for="password" class="col-sm-2 control-label">Password</label>
                   <div class="col-sm-4">
                       <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                   </div>
               </div>
               <div class="form-group">
                   <div class="col-sm-offset-2 col-sm-4">
                       <div class="checkbox">
                           <label>
                               <input type="checkbox" name="remember" id="remember"> Remember me
                           </label>
                       </div>
                   </div>
               </div>
               <div class="form-group">
                   <div class="col-sm-offset-2 col-sm-10">
                       <button type="submit" name="submit" class="btn btn-default">Sign in</button>
                   </div>
               </div>
           
         </div>
     }
    @Styles.Render("~/Content/css")

EntertainmentTrackerPersonal/Views/Shared/_Layout.Phone.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @Styles.Render("~/Content/mobileCss", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div data-role="page" data-theme="b">
            <div data-role="header">
                <div>This is Mobile View</div>
                @if (IsSectionDefined("Header")) {
                    @RenderSection("Header")
                } else {
                    <h1>@ViewBag.Title</h1>
                    @Html.Partial("_LoginPartial")
                }
            </div>
            <div data-role="content">
                @RenderBody()
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        @RenderSection("scripts", required: false)
    </body>
</html>

EntertainmentTrackerPersonal/Views/Shared/_Layout.Tablet.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @Styles.Render("~/Content/mobileCss", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div data-role="page" data-theme="b">
            <div data-role="header">
                <div>This is Tablet View</div>
                @if (IsSectionDefined("Header")) {
                    @RenderSection("Header")
                } else {
                    <h1>@ViewBag.Title</h1>
                    @Html.Partial("_LoginPartial")
                }
            </div>
            <div data-role="content">
                @RenderBody()
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        @RenderSection("scripts", required: false)
    </body>
</html>

EntertainmentTrackerPersonal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title MTS(One)</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")       
    </head>

    <body>
        <h1 class="mainTitle">Movie Tracking System(One)</h1>
        <header>
            <div class="content-wrapper">
              
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <a class="navbar-brand" style="padding:5px 15px;" href='@Url.Action("UserHome", "Users")'>
                                <img src='@Url.Content("~/Images/logos/pLogo.jpg")' />
                            </a>
                            
                          
                        </div>
                        <ul id="menu"  class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "UserHome", "Users")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li class="divider"></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body" class="container">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content3 clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year MTS(One)</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

EntertainmentTrackerPersonal/Views/TVShows/AddTVShows.cshtml
@{
    ViewBag.Title = "Add tvshows";
}

<h4>add TVShows</h4>

EntertainmentTrackerPersonal/Views/TVShows/Index.cshtml
@{
    ViewBag.Title = "TV shows Home page";
}

<h4> blah</h4>

EntertainmentTrackerPersonal/Views/TVShows/TVShowsLibrary.cshtml
@{
    ViewBag.Title = "TVShows Lib";
}

<h4>TVShows you have added</h4>

EntertainmentTrackerPersonal/Views/Users/UserHome.cshtml
@{
    ViewBag.Title = "User HomePage";
}
<div id="topContainer" class="userHomeTopContainer">
<ul class="nav nav-tabs nav-justified">
    <li class="active">@Html.ActionLink("User Home", "UserHome", "Users")</li>
    <li>@Html.ActionLink("Add TV Shows", "AddTVShows", "TVShows")</li>
    <li>@Html.ActionLink("Add Books", "AddBooks", "Books")</li>
    <li>@Html.ActionLink("Add Animes", "AddAnimes", "Animes")</li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Your Library's <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a>@Html.ActionLink("TVShows Library", "TVShowsLibrary", "TVShows")</a></li> 
            <li>@Html.ActionLink("Books Library", "BooksLibrary", "Books")</li> 
            <li>@Html.ActionLink("Animes Libary", "AnimesLibrary", "Animes")</li> 
        </ul>

    </li>
</ul>
</div>
<div id="mainContainer">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
    </div>

</div>